### PR TITLE
Fix comments

### PR DESCRIPTION
**Pull request by psyk00**

### CODE REVIEW

**Comment by psyk00** [comment]
Hi!!
No, looks like there is a some wrong comments here ^^:
http://prntscr.com/nxzdmv
http://prntscr.com/nxze3u

**Comment by Gabyfle** [comment]
Hi!

I think it's a problem related to your code editor. Take a look here : https://github.com/Gabyfle/gName-Changer/blob/master/gname-changer/lua/autorun/gname_changer_config.lua

There isn't any problem on my end. Tables are loaded without any problems.

**Comment by psyk00** [comment]
hummm, in lua, the comment format is:
--[[
 your comment
]]
or
-- your comment
on my screen, the comment are not in a good way, right? :p

**Comment by Gabyfle** [comment]
> 
> 
> hummm, in lua, the comment format is:
> --[[
> your comment
> ]]
> or
> -- your comment
> on my screen, the comment are not in a good way, right? :p

That's right, so when I'm doing this : 
```lua
--[[ starting here a new comment on several lines
local name = 'gName-Changer' <-- this will not be executed by the parser, cuz it's inside the comment
]]-- ending the multiple-lines comment and starting a one-line comment
local name = 'Yolo Swag' -- <-- this will be executed

print(name) -- display : Yolo Swag
```
I'm following the comments format of Lua.

**Pull request merged**
